### PR TITLE
Baseline react implementation

### PR DESCRIPTION
**Pull request by peol**
**Preview URL: https://deploy-preview-17--experimenter.netlify.com/?engine_url=wss://scalingbackend.qlikcore.com/app/doc/25ff2c3d-54de-449f-9301-4794a05160d2**

This is a proposal to move over to a React implementation of this project. The main reasons being:

* Feedback on the code quality (hard to understand and maintain)
* Sharing solutions (i.e. code) between this and other projects

Unimplemented as of now:

* Brushing a field (highlighting it elsewhere)
* Introduction guide

A substantial amount of the code is taken from the catwalk project, and can be shared between them in the future, reducing the code base a lot:

* Everything in `./src/components/abstractions`
* The filterbox code can be replaced with the upcoming shared work

### CODE REVIEW

**Review by bjornwiberg — APPROVED** [review]
Nice initiative, lgtm! 👍

**Review by hrigner — APPROVED** [review]
Great work @peol! And yes, we should probably share the HOCs (with-objects) and the context object (AppProvider) with Catwalk.. and with anyone else :)

**Comment by aalteirac** [comment]
Looks great !

**Review by aalteirac — APPROVED** [review]

**Comment by rjriel** [comment]
is there a reason this hasn't been moved to master?

**Comment by peol** [comment]
@rjriel As mentioned in the PR there are some things that are unimplemented. I had also misinterpreted and the top "list of fields" is actually a table on master so that needs work too.

Then it's a matter of opinion, web components vs React, but personally I think we gain too much from sharing code base with other projects than staying with web components.

**Pull request closed without merging**
